### ISSUE TITLE
The unusual timestamp section

### ISSUE THREAD

**Issue by AE-Hertz** [DeadmanAbir/AgentGenesis#101]
**Describe the bug**
The issue with date and time having really large size thats is not ideal and not looking good with the awesome design of the site.

**To Reproduce**
1. Go to 'site'
2. Click on 'blog section'
3. Scroll down to 'any blog'
4. See big timestamp section

**Expected behavior**
its should be settle.

**Screenshots**
![Screenshot 2024-10-29 225545](https://github.com/user-attachments/assets/cc322dea-e8ab-4cfd-bcc6-44cc5d3616a0)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Assign me this under hacktoberfest and gssoc-ext.

**Comment by DeadmanAbir** [comment]
issue #58 already mentions this
