### ISSUE TITLE
Feat - Adding FAQ Section

### ISSUE THREAD

**Issue by dev129** [DeadmanAbir/AgentGenesis#104]
**Issue Title:** Feature Request: FAQ Section Design
Hi @DeadmanAbir 
---

**Is your feature request related to a problem? Please describe.**
Currently, users may face difficulty finding quick answers to common questions, which can impact user satisfaction and increase support requests.

**Describe the solution you'd like**
An FAQ section that provides clear, concise answers to frequently asked questions, organized in a user-friendly layout to improve accessibility and enhance the user experience.

**Describe alternatives you've considered**
Considered options include linking to an external knowledge base or integrating a chatbot for queries. However, these alternatives may not provide the same immediate clarity as an in-app FAQ section.

**Additional context**
1. **Purpose of this feature:** This feature is designed to make it easy for users to find answers quickly, reducing confusion and enhancing user satisfaction.

2. **Benefits of this feature:** Users can find solutions to common issues without needing additional support, thus reducing support load and improving self-service options.

3. **Targeted user needs or scenarios:** This feature targets users who are looking for quick answers on their own, such as new users or those encountering minor issues.

4. **User interaction with this feature:** The FAQ section will be accessible through a dedicated section or sidebar, with collapsible questions to ensure a clean and manageable interface.

5. **Potential implementation challenges:** Challenges include organizing questions effectively, optimizing for mobile devices, and ensuring answers are easy to understand.

6. **Impact on other functionalities:** This feature may affect navigation design, requiring a dedicated link or icon that is easily accessible but not intrusive.

7. **Security or privacy considerations:** No additional security considerations are expected for this static FAQ section.

8. **Support for customization:** The FAQ section could support customizable categories or expandable/collapsible question lists to make it easy for users to browse relevant topics.

9. **Additional documentation or support:** The FAQ will include a search bar or filter option to help users quickly locate relevant answers.

**Comment by DeadmanAbir** [comment]
Already have that in [Here](https://agentgenesis.dev/components)
