### ISSUE TITLE
Feat- Adding Review Section 

### ISSUE THREAD

**Issue by dev129** [DeadmanAbir/AgentGenesis#105]
**Issue Title:** Feature Request: Review Section Design
Hi @DeadmanAbir 
---

**Is your feature request related to a problem? Please describe.**
Users lack a dedicated space to view and share feedback, which limits transparency and prevents potential users from gaining insights into real user experiences.

**Describe the solution you'd like**
A review section that allows users to post, read, and interact with reviews, helping build trust and provide insights on the product's value.

**Describe alternatives you've considered**
Considered embedding third-party review platforms or linking to external review sites, but these options reduce the in-app experience and may not align with the platform’s design and user flow.

**Additional context**
1. **Purpose of this feature:** To provide a dedicated space for user feedback and showcase user satisfaction, helping others make informed decisions.

2. **Benefits of this feature:** It increases transparency, builds trust, and adds value by displaying real user experiences, contributing to community engagement.

3. **Targeted user needs or scenarios:** This feature is useful for users who want to share feedback and for prospective users evaluating the product.

4. **User interaction with this feature:** Users will access this section via a designated "Reviews" tab or link. They can post a review, read others’ feedback, and filter or sort reviews based on relevance, rating, or recency.

5. **Potential implementation challenges:** Ensuring reviews are moderated, maintaining user privacy, and preventing spam or irrelevant content may pose challenges.

6. **Impact on other functionalities:** This feature may require navigation adjustments and alignment with the overall design language, especially in profile or product pages.

7. **Security or privacy considerations:** Review content should be moderated to prevent inappropriate language and privacy issues. User data related to reviews should be handled according to privacy policies.

8. **Support for customization:** The review section may include options for users to rate with stars, leave comments, or use emojis, adding personalization and interactivity.

9. **Additional documentation or support:** A simple guide on leaving a review may be included, and filtering options will help users quickly find relevant reviews.

**Comment by DeadmanAbir** [comment]
not needed for now
