### ISSUE TITLE
Add a contact us page, check description 

### ISSUE THREAD

**Issue by AE-Hertz** [DeadmanAbir/AgentGenesis#108]
**Is your feature request related to a problem? Please describe.**
implement a contact us page that have same theme like the project,
- the current contact us button directly opens outlook in windows,
- i will handle this for different operating systems.
- implement the details on contact page so user can save contact information directly.

@DeadmanAbir can you assign me this issue, and i expect a level3 for this..

**Comment by DeadmanAbir** [comment]
Not needed for now!
