### ISSUE TITLE
add a credit page, check description 

### ISSUE THREAD

**Issue by AE-Hertz** [DeadmanAbir/AgentGenesis#109]
**Is your feature request related to a problem? Please describe.**
add a credit page to show the dev work,
- i will make a new page for credits
- link with github to automate the process of dev addition, (as the project is good and growing)
- will keep the same theme as current to have consistency 

Screenshot:
![Screenshot 2024-11-04 185741](https://github.com/user-attachments/assets/9fa82495-b066-42f8-bf80-a397d0001fee)

@DeadmanAbir can you assgin me this issue, i expect a level3 for this.

**Comment by DeadmanAbir** [comment]
> **Is your feature request related to a problem? Please describe.** add a credit page to show the dev work,
> 
> * i will make a new page for credits
> * link with github to automate the process of dev addition, (as the project is good and growing)
> * will keep the same theme as current to have consistency
> 
> Screenshot: ![Screenshot 2024-11-04 185741](https://private-user-images.githubusercontent.com/93651229/382773470-9fa82495-b066-42f8-bf80-a397d0001fee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTEyNzksIm5iZiI6MTczMDc5MDk3OSwicGF0aCI6Ii85MzY1MTIyOS8zODI3NzM0NzAtOWZhODI0OTUtYjA2Ni00MmY4LWJmODAtYTM5N2QwMDAxZmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA3MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOGE5ZDdmNjY2MzhiMGIwNzdlNjcxZTMwZThmYjQ1ZTczNThkMjkyMzg0NWFlNmMxNjUxMmIzOTkxYWI3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JLKLRR6Uz9dqJtl_z96dGIRldZaYY93JyybpQO4T5BQ)
> 
> @DeadmanAbir can you assgin me this issue, i expect a level3 for this.

What content you 're thinking to add onto this credit page?

**Comment by AE-Hertz** [comment]
> > **Is your feature request related to a problem? Please describe.** add a credit page to show the dev work,
> > 
> > * i will make a new page for credits
> > * link with github to automate the process of dev addition, (as the project is good and growing)
> > * will keep the same theme as current to have consistency
> > 
> > Screenshot: ![Screenshot 2024-11-04 185741](https://private-user-images.githubusercontent.com/93651229/382773470-9fa82495-b066-42f8-bf80-a397d0001fee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3OTEyNzksIm5iZiI6MTczMDc5MDk3OSwicGF0aCI6Ii85MzY1MTIyOS8zODI3NzM0NzAtOWZhODI0OTUtYjA2Ni00MmY4LWJmODAtYTM5N2QwMDAxZmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA3MTYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkOGE5ZDdmNjY2MzhiMGIwNzdlNjcxZTMwZThmYjQ1ZTczNThkMjkyMzg0NWFlNmMxNjUxMmIzOTkxYWI3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JLKLRR6Uz9dqJtl_z96dGIRldZaYY93JyybpQO4T5BQ)
> > @DeadmanAbir can you assgin me this issue, i expect a level3 for this.
> 
> What content you 're thinking to add onto this credit page?

i am thinking to have:
- the list of frameworks we are using in this project
- the information sources 
- the contributors who contributed in this project

and i am also open to ideas for any other items.

**Comment by DeadmanAbir** [comment]
I think the list that you're mentioning is already in github readme and we don't need the contributors to show in main website for now.
