### ISSUE TITLE
UI: update the blog page

### ISSUE THREAD

**Issue by AE-Hertz** [DeadmanAbir/AgentGenesis#110]
**Is your feature request related to a problem? Please describe.**
the current blog page is not making with the current theme of the site,

**Describe the solution you'd like**
i will make the blog page to match the current theme, and implement the dark mode optionin it.

![Screenshot 2024-11-05 193034](https://github.com/user-attachments/assets/49830019-0f2a-4344-800a-43d9c36f1cc0)

Assign me this.

**Comment by DeadmanAbir** [comment]
> **Is your feature request related to a problem? Please describe.** the current blog page is not making with the current theme of the site,
> 
> **Describe the solution you'd like** i will make the blog page to match the current theme, and implement the dark mode optionin it.
> 
> ![Screenshot 2024-11-05 193034](https://private-user-images.githubusercontent.com/93651229/383176505-49830019-0f2a-4344-800a-43d9c36f1cc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MTY1NDksIm5iZiI6MTczMDgxNjI0OSwicGF0aCI6Ii85MzY1MTIyOS8zODMxNzY1MDUtNDk4MzAwMTktMGYyYS00MzQ0LTgwMGEtNDNkOWMzNmYxY2MwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE0MTcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMTU1MzkzOWFlMDM0NmZkYTQxODQxYmFiYWQzNDVhZjYzNTk1ZTdmM2M4NmU0MTU0OTk0ZGM0MWYwYTlmZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1RFGGsxI5Dr-Q0el1Kq71PBmB6IDWX02BJFIyPANxXw)
> 
> Assign me this.

go ahead

**Comment by DeadmanAbir** [comment]
updates?

**Comment by AE-Hertz** [comment]
> updates?

Yes I am working on it. Few things left to handle. Soon I will request for review.
