### ISSUE TITLE
The Footer Text

### ISSUE THREAD

**Issue by sachinggsingh** [DeadmanAbir/AgentGenesis#111]
**Describe the bug**
The Footer Text AGENTGENESIS is very less visible in the Light mode which is visible in the Dark mode

**Expected behavior**
It should be also seen in the Light mode also

**Screenshots**
**In Dark mode**
![Screenshot 2024-11-05 195149](https://github.com/user-attachments/assets/d438a3fc-b0a0-40d4-9b0d-21732e81c2f9)

**In light mode**
![Screenshot 2024-11-05 195134](https://github.com/user-attachments/assets/68cec680-2133-4d5d-94e8-ab61a0b29f4b)

**Comment by DeadmanAbir** [comment]
> [sachinggsingh](/sachinggsingh)

waana work on it?

**Comment by sachinggsingh** [comment]
Yesss wanna work on it

**Comment by DeadmanAbir** [comment]
> Yesss wanna work on it

Go ahead

**Comment by sachinggsingh** [comment]
@DeadmanAbir  sorry uh can unassign me this issue I don't have any expertise in the TypeScript wont be able to do it
