### ISSUE TITLE
[FEAT] : Design Eye-Catching Progress Bar on scroll and add a Back to top button for UI Aesthetics

### ISSUE THREAD

**Issue by Edasgh** [DeadmanAbir/AgentGenesis#115]
:red_circle: Add a progress bar and a back to top button in all the pages
:red_circle: **Enhancement Aim** : I propose the development of a visually appealing progress bar  and a back to top button that seamlessly integrates with the overall UI aesthetics of the application.
:red_circle: **Changes** :
- Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process, and a back to top button helps users to go back to the top-part improving usability and navigation.

- Improved Aesthetics: Customizing the  progress bar and the back to top button to match the UI enhances the overall look and feel of the application, making it more attractive to users.

- Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.

Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

**Comment by DeadmanAbir** [comment]
Attach some screenshots as an example

**Comment by Edasgh** [comment]
> Attach some screenshots as an example
Like the on scroll progress bar and the back to top button here
![Screenshot 2024-11-08 084950](https://github.com/user-attachments/assets/6f4c5714-48ef-430d-be10-86c88705d3c5)

**Comment by DeadmanAbir** [comment]
Back to top button is already under work, and we don't think we need a progress bar like the one in screenshot.
