### ISSUE TITLE
3rd pricing card breaking in mobile view

### ISSUE THREAD

**Issue by DeadmanAbir** [DeadmanAbir/AgentGenesis#32]
In the  /pricing page the 3rd pricing card i.e the `Custom Solutions` card is breaking in mobile view.

**Expected behavior**
Should have adequate padding between text and button.

**Screenshots**

![Screenshot_20240818-163455](https://github.com/user-attachments/assets/02384508-c40d-4084-a88b-17a3a2704c38)

**Smartphone (Infinix):**
 - Device: [e.g. Infinix Note 12i]
 - Browser [Chrome]

**Comment by faisal004** [comment]
#33
