### ISSUE TITLE
Fix Typo in Chat Models Section

### ISSUE THREAD

**Issue by khaulanauman** [DeadmanAbir/AgentGenesis#36]
There is a typo in the "Chat Models" section where "differnt" should be corrected to "different."

**Comment by dev628140** [comment]
There are two typos to be fixed in "Chat Models" section where "Anthrotopic" should be "Anthropic" and "differnt" should be "different".

**Comment by khaulanauman** [comment]
thankyou for adding to that- i will fix that - once assigned - as well

**Comment by DeadmanAbir** [comment]
@khaulanauman you can create a PR for this.
