### ISSUE TITLE
Improve UI/UX Design

### ISSUE THREAD

**Issue by khaulanauman** [DeadmanAbir/AgentGenesis#37]
The current design lacks contrasting colors, making the interface look bland and less engaging.
![image](https://github.com/user-attachments/assets/4fade286-5a34-493d-81b7-3ea1b1cd55e1)
change the glowing background to a more contrasting color, like the blue and purple lines from the hero section, which would make the interface more vibrant and visually appealing.

**Comment by DeadmanAbir** [comment]
@khaulanauman can you just provide a screenshot both in dark and light mode, regarding what kind of UI changes you're referring to.

**Comment by khaulanauman** [comment]
![image](https://github.com/user-attachments/assets/b86aeb04-ed92-49c2-8d5f-578481c20e57)
![image](https://github.com/user-attachments/assets/ed11475f-edd2-4b19-88b6-961a938bdb73)

a very rough design - just to give u an idea

**Comment by DeadmanAbir** [comment]
> ![image](https://private-user-images.githubusercontent.com/114153459/373861219-b86aeb04-ed92-49c2-8d5f-578481c20e57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjgxMTgsIm5iZiI6MTcyODEyNzgxOCwicGF0aCI6Ii8xMTQxNTM0NTkvMzczODYxMjE5LWI4NmFlYjA0LWVkOTItNDljMi04ZDVmLTU3ODQ4MWMyMGU1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xY2E3MzkxYjkyNTE3MDRhNGJjNzE1YzcwMzRhZDU1NDk3YWQ5OGFmZWI5MDczM2ExYTVjNTEzMzc4MzU0ZGZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DWkF86i-DUA_TKievP3BqEPfaMbvQsYGP87VtKKI3TE) ![image](https://private-user-images.githubusercontent.com/114153459/373861454-ed11475f-edd2-4b19-88b6-961a938bdb73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgxMjgxMTgsIm5iZiI6MTcyODEyNzgxOCwicGF0aCI6Ii8xMTQxNTM0NTkvMzczODYxNDU0LWVkMTE0NzVmLWVkZDItNGIxOS04OGI2LTk2MWE5MzhiZGI3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNVQxMTMwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjgwOTBjMGI1YzUwYTc3NDI0NjI0MmRmZWNhODMwYWQ2ZjIxYzU5NDVlNWM1ZWMxZGZmZmY2NmRlNDRmMTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5JopwA0pZaoxHs-_rIbHczdILnLXLrixdjGq265RhGU)
> 
> a very rough design - just to give u an idea the color can of course be adjusted to ensure a sleek design
looks good to me to start atleast.

**Comment by khaulanauman** [comment]
Why was the issue closed?

**Comment by DeadmanAbir** [comment]
> Why was the issue closed?

Issue was assigned more than a week still no response or updates so we decided to move further.
