### ISSUE TITLE
Adding blog section with fetching hashnode  blogs

### ISSUE THREAD

**Issue by abhishekpanthee** [DeadmanAbir/AgentGenesis#38]
**Is your feature request related to a problem? Please describe.**
No not a problem but a feature mostly needed for these type of organizational website 

**Describe the solution you'd like**
What ia want to do is to use mdx to render and create blog section with custom uid for different blog articles 

**Describe alternatives you've considered**
I though of using  the same component using json to load uid and file content but that is a haste

**Comment by DeadmanAbir** [comment]
> **Is your feature request related to a problem? Please describe.** No not a problem but a feature mostly needed for these type of organizational website
> 
> **Describe the solution you'd like** What ia want to do is to use mdx to render and create blog section with custom uid for different blog articles
> 
> **Describe alternatives you've considered** I though of using the same component using json to load uid and file content but that is a haste

We have planned to write our blogs on hashnode so, checkout hashnode api, how we can fetch blogs from an specific account and render them into our frontend.
