### ISSUE TITLE
adding rate us option

### ISSUE THREAD

**Issue by Aditijainnn** [DeadmanAbir/AgentGenesis#39]
in the bottom adding and option of feedback/rate us
please assign this to me under gssoc ext and hactoberfest 
![image](https://github.com/user-attachments/assets/0704162b-52d6-4306-830c-7f6e49bfea7b)
also the top dashboard needs improvement

**Comment by DeadmanAbir** [comment]
> Quote reply

Suggest the improvements for dashboard.

we already have star us on github so what's the relevancy of adding rate us, and where we gonna store this ratings?
