### ISSUE TITLE
Add Missing Meta Tags for SEO Enhancement 

### ISSUE THREAD

**Issue by myselfshivams** [DeadmanAbir/AgentGenesis#40]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

- Title tags
- Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag
- 
@DeadmanAbir  Please assign this issue to me (@myselfshivams).

Labels:
- GSSoC
- Hacktoberfest

**Comment by DeadmanAbir** [comment]
> The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:
> 
> * Title tags
> * Description tags
> * Keywords tags
> * Open Graph tags for social media sharing
> * Robots meta tag
> 
> @DeadmanAbir Please assign this issue to me (@myselfshivams).
> 
> Labels:
> 
> * GSSoC
> * Hacktoberfest

hey we have setted up dynamic meta tags for every component, you can check that by sharing any component link over whatsapp or discord.
