### ISSUE TITLE
Change 'Docs' to 'Components' and Add 'Contact Us'

### ISSUE THREAD

**Issue by faisal004** [DeadmanAbir/AgentGenesis#42]
Description:
There are two updates needed in the Navbar component:

1.Change Heading:
- Update the Navbar heading from "Docs" to "Components".
- Update the configuration in config.js to change the route from /docs to /components.

2.Add 'Contact Us':

- Add a new menu item for "Contact Us" in the Navbar to improve user accessibility to contact information.

These changes will enhance the clarity and functionality of the Navbar, ensuring users can easily navigate to the relevant sections and access support.

Acceptance Criteria:

- The Navbar should display "Components" instead of "Docs".
- The route in config.js should be updated accordingly.
- A "Contact Us" option should be visible in the Navbar.

**Comment by Yashhuc** [comment]
Hey, I would like to work on this issue. Please assign me this.

**Comment by faisal004** [comment]
Ok take it @Yashhuc

**Comment by DeadmanAbir** [comment]
Hey @Yashhuc  what's the update? Give a update within 24 hrs otherwise we will reassign someone.

**Comment by Yashhuc** [comment]
I have raised the PR.
