### ISSUE TITLE
Default Tab for LinkedIn Agent Should be Playground tab

### ISSUE THREAD

**Issue by faisal004** [DeadmanAbir/AgentGenesis#43]
Description:
The current implementation of the LinkedIn agent defaults to a "Preview "tab instead of the "Playground" tab.
Steps to Reproduce:
- Navigate to the LinkedIn agent section(https://agentgenesis.dev/docs/components/linkedinAgent).
- Observe the default tab is Preview Tab.
- Expectation: The Playground tab should load by default.

**Comment by aryanbroy** [comment]
if no one is working on this can you assign this to me?

**Comment by faisal004** [comment]
ok take it
