### ISSUE TITLE
 Implement Per-User Rate Limiting for LinkedIn Agent Access

### ISSUE THREAD

**Issue by DeadmanAbir** [DeadmanAbir/AgentGenesis#44]
Implement rate limiting to the backend of our [LinkedIn Agent](https://agentgenesis.dev/docs/components/linkedinAgent), restricting each unique user to 2 accesses every 24 hours in the playground. This is crucial as we are providing in-house API keys for LLMs and Proxycurl, necessitating controlled usage to prevent abuse.

- Implement rate limiting logic within `src/app/api/agent/route.ts`
- Can use any open source external libraries as per requirement.
- Before starting provide an overall architecture, how you're going to implement this and the libraries used.

By implementing this rate-limiting feature, we enhance the security and reliability of our LinkedIn Agent backend, ensuring resources are used appropriately and service availability is maintained for all users.

**Comment by priyanshuverma-dev** [comment]
Hi @DeadmanAbir,

May I work on this issue will solve it by using `redis` to save user's ip 
With `RateLimiterRedis`
It is very easy 

We can customize it like 
```ts
const rateLimiter = new RateLimiterRedis({
  storeClient: redisClient,
  keyPrefix: 'rateLimiter',
  points: 2, // 2 requests
  duration: 24 * 60 * 60, // 24 hours
});
```

**Comment by DeadmanAbir** [comment]
> Hi @DeadmanAbir,
> 
> May I work on this issue will solve it by using `redis` to save user's ip With `RateLimiterRedis` It is very easy
> 
> We can customize it like
> 
> ```ts
> const rateLimiter = new RateLimiterRedis({
>   storeClient: redisClient,
>   keyPrefix: 'rateLimiter',
>   points: 2, // 2 requests
>   duration: 24 * 60 * 60, // 24 hours
> });
> ```



> Hi @DeadmanAbir,
> 
> May I work on this issue will solve it by using `redis` to save user's ip With `RateLimiterRedis` It is very easy
> 
> We can customize it like
> 
> ```ts
> const rateLimiter = new RateLimiterRedis({
>   storeClient: redisClient,
>   keyPrefix: 'rateLimiter',
>   points: 2, // 2 requests
>   duration: 24 * 60 * 60, // 24 hours
> });
> ```

Hey do we have to deploy  redis by our own or it's free of service?

**Comment by priyanshuverma-dev** [comment]
@DeadmanAbir We have to deploy it our self but we can use a free tier from `render.com` or other because we will be using it for only ip rating

**Comment by priyanshuverma-dev** [comment]
@DeadmanAbir May I implement the fix

**Comment by priyanshuverma-dev** [comment]
@DeadmanAbir 

We can use vercel KV also as it depends on budget what to use. I can implement this for production you need to figure out.
Hope you understand.

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir
> 
> We can use vercel KV also as it depends on budget what to use. I can implement this for production you need to figure out. Hope you understand.

Ok go ahead, keeping in mind that we will use Vercel KV.

**Comment by priyanshuverma-dev** [comment]
Hello @DeadmanAbir,
I am implementing rating limiting to `/api/agent`
What should be rate limiting

5 requests from the same IP in 3600 seconds.

OR other. Let me know

**Comment by DeadmanAbir** [comment]
> Hello @DeadmanAbir, I am implementing rating limiting to `/api/agent` What should be rate limiting
> 
> 5 requests from the same IP in 3600 seconds.
> 
> OR other. Let me know
2 request from the same IP in 86400 seconds

**Comment by priyanshuverma-dev** [comment]
@DeadmanAbir 
How to i debug let me know about the product first
How rate limiting is helping as I have to put my own api keys in place holder to work??

**Comment by DeadmanAbir** [comment]
> priyanshuverma

2 request from the same IP in 86400 seconds.

Also create `/api/agent/core.ts`
add all the code into that file and import and use that in `route.ts` .

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir How to i debug let me know about the product first How rate limiting is helping as I have to put my own api keys in place holder to work??

we will change the flow from providing own api key to our inhouse keys, and when we will change into that we have implement a rate limit to prevent over use of our own APIs.

**Comment by priyanshuverma-dev** [comment]
ok we have only user's IP for identification 

@DeadmanAbir
