### ISSUE TITLE
Issue Title: "Add Cursor-Following Animation"

### ISSUE THREAD

**Issue by AswaniBolisetti** [DeadmanAbir/AgentGenesis#46]
@DeadmanAbir 
Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.

I’d like to work on adding this feature. Please assign this issue to me.

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir Issue Description: The website currently lacks interactive design elements that enhance user experience. I propose adding a cursor-following animation to create dynamic interactions where design elements move along with the mouse cursor, providing a more engaging and visually appealing experience.
> 
> I’d like to work on adding this feature. Please assign this issue to me.

show us a preview of what you are trying to add or an example link.

**Comment by AswaniBolisetti** [comment]
@DeadmanAbir 

https://github.com/user-attachments/assets/bd9a82b6-a3e8-4780-bc55-3f527768a292

like this, and there are many other styles for cursor animation

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir
> 
>  cursor6.mp4 
> like this, and there are many other styles for cursor animation

Hey while this thing looks good in web app, but it will going to be a complete mess when it comes to mobile app view, because in mobile the hover features doesn't work properly.

**Comment by AswaniBolisetti** [comment]
@DeadmanAbir that's ok,
