### ISSUE TITLE
Search fix for Blogs

### ISSUE THREAD

**Issue by abhishekpanthee** [DeadmanAbir/AgentGenesis#48]
**Is your feature request related to a problem? Please describe.**
Yes problem is there in my previous  work of blog section I just didn't happen to see that 
so my problem is that search is not working for blogs  

**Describe the solution you'd like**
Solution is solving it 

**Describe alternatives you've considered**
Nah none 

**Additional context**
I want to work on that do assign me the labels 
 
 
 
 also i would like to work on this 
 https://github.com/DeadmanAbir/AgentGenesis/issues/42
  do ping me if possible

**Comment by DeadmanAbir** [comment]
> **Is your feature request related to a problem? Please describe.** Yes problem is there in my previous work of blog section I just didn't happen to see that so my problem is that search is not working for blogs
> 
> **Describe the solution you'd like** Solution is solving it
> 
> **Describe alternatives you've considered** Nah none
> 
> **Additional context** I want to work on that do assign me the labels
> 
> also i would like to work on this #42 do ping me if possible

fix this for now, and for issur #42  I will tag you there.
