### ISSUE TITLE
Issue Title: "Add Footer Section"

### ISSUE THREAD

**Issue by AswaniBolisetti** [DeadmanAbir/AgentGenesis#52]
@DeadmanAbir 
Issue Description: The website currently lacks a footer section. I propose adding a footer that includes useful links, contact information, social media icons, and other relevant details to improve navigation and provide users with easy access to important resources.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir Issue Description: The website currently lacks a footer section. I propose adding a footer that includes useful links, contact information, social media icons, and other relevant details to improve navigation and provide users with easy access to important resources.
> 
> I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

The footer we have is okay for now, we don't think we need a new one , if we need we will  raise a issue in future.
