### ISSUE TITLE
Refactor Blog UI 

### ISSUE THREAD

**Issue by DeadmanAbir** [DeadmanAbir/AgentGenesis#58]
#### Objective:
We aim to enhance the user experience and visual appeal of the [Agentgenesis Blog](https://agentgenesis.dev/blogs) by refactoring the UI. For this update, we'll draw inspiration from the clean and modern design of [Accertinity Blog](https://www.aceternity.com/blog). 

#### Scope:
- Refactor the blog's front-end to closely match the look and feel of Accertinity’s blog.
- Use **ShadCN UI** and **TailwindCSS** exclusively to implement the changes.
- Feel free to incorporate design elements and patterns from UI libraries such as **Accertinity UI**, **Magic UI**, etc., while maintaining consistency with the inspirational design.

#### Deliverables:
- A refined UI that improves readability, responsiveness, and overall aesthetics.
- Ensure that the new components and layouts integrate seamlessly with the existing blog structure.

**Comment by aasiflm10** [comment]
@DeadmanAbir  I would like to work on this issue.

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir I would like to work on this issue.

Okay you are assigned.

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir I would like to work on this issue.

@aasiflm10  any updates?

**Comment by shubhagarwal1** [comment]
Hey @DeadmanAbir please asssign me this task i can complete this with efficiency.

**Comment by DeadmanAbir** [comment]
> Hey @DeadmanAbir please asssign me this task i can complete this with efficiency.

okay take it

**Comment by shubhagarwal1** [comment]
Hey @DeadmanAbir thankyou for the opportunity

**Comment by shubhagarwal1** [comment]
Hey @DeadmanAbir can we connect stuck with this isue 

> Hey @DeadmanAbir thankyou for the opportunity
<img width="969" alt="Screenshot 2024-10-26 at 8 22 53 PM" src="https://github.com/user-attachments/assets/26c37c91-a8d7-47b7-ab3d-c56f31825abb">

Hey @DeadmanAbir i am stuck witht this error in the console can you please help me

**Comment by DeadmanAbir** [comment]
> Hey @DeadmanAbir can we connect stuck with this isue
> 
> > Hey @DeadmanAbir thankyou for the opportunity
> 
> <img alt="Screenshot 2024-10-26 at 8 22 53 PM" width="969" src="https://private-user-images.githubusercontent.com/105449260/380430843-26c37c91-a8d7-47b7-ab3d-c56f31825abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTUxNzMsIm5iZiI6MTcyOTk1NDg3MywicGF0aCI6Ii8xMDU0NDkyNjAvMzgwNDMwODQzLTI2YzM3YzkxLWE4ZDctNDdiNy1hYjNkLWM1NmYzMTgyNWFiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxNTAxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMGIzMTQyOGRhNGRmMmE1NDZiZDZmMjhjZDQ1YWY5OGYzZjUzYTNhMjUxYWNiZDlmMWQxZTc0MWQwMGYyYzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.a-cYaeKwaBDhWnzjAqvU9CAFJkGWNG9VgNzRDLkwbfU">
> Hey @DeadmanAbir i am stuck witht this error in the console can you please help me

Have you configured the env files properly? Check `.env.sample` file and then create a `.env` file of yours.

**Comment by DeadmanAbir** [comment]
Any Progress @shubhagarwal1

**Comment by shubhagarwal1** [comment]
> Any Progress @shubhagarwal1

Not abel to proceed as stuck with the same erro, can we connect on discord for once.

**Comment by DeadmanAbir** [comment]
Sure, `deadmanabir` my username

**Comment by DeadmanAbir** [comment]
> > Any Progress @shubhagarwal1
> 
> Not abel to proceed as stuck with the same erro, can we connect on discord for once.

updates?

**Comment by DeadmanAbir** [comment]
> > > Any Progress @shubhagarwal1
> > 
> > 
> > Not abel to proceed as stuck with the same erro, can we connect on discord for once.
> 
> updates?

@shubhagarwal1 ??

**Comment by shubhagarwal1** [comment]
> > > > Any Progress @shubhagarwal1
> > > 
> > > 
> > > Not abel to proceed as stuck with the same erro, can we connect on discord for once.
> > 
> > 
> > updates?
> 
> @shubhagarwal1 ??

hey can we onnect on disdcord i have texted you

**Comment by shubhagarwal1** [comment]
> > > > > Any Progress @shubhagarwal1
> > > > 
> > > > 
> > > > Not abel to proceed as stuck with the same erro, can we connect on discord for once.
> > > 
> > > 
> > > updates?
> > 
> > 
> > @shubhagarwal1 ??
> 
> hey can we onnect on disdcord i have texted you

will deliver this by today
