### ISSUE TITLE
Remove Blog List from Sidebar while Preserving Search Functionality

### ISSUE THREAD

**Issue by DeadmanAbir** [DeadmanAbir/AgentGenesis#60]
Currently, the sidebar at https://agentgenesis.dev/components displays a list of **blogs** in its bottom section. This PR aims to remove this blog list section from the sidebar without affecting the site's overall blog search functionality.

Objectives:
1. Remove the blog list section from the sidebar
2. Ensure the search functionality for blogs remains intact

Steps to Implement:
1. Locate the sidebar configuration in the file:
   `https://github.com/DeadmanAbir/AgentGenesis/blob/main/src/config/doc.ts`

2. Identify the section in the configuration that generates the blog list in the sidebar

3. Remove or comment out the code responsible for rendering the blog list

4. Verify that the removal doesn't impact the search bar's ability to find and display blog posts

5. Test thoroughly to ensure no unintended side effects on the sidebar's layout or functionality

6. Update any related documentation or comments if necessary

Acceptance Criteria:
- The blog list no longer appears in the sidebar on the components page
- Users can still search for and access blog posts using the search bar
- The sidebar's overall structure and other functionalities remain intact
- No regression in site performance or user experience

Additional Notes:
- If removing the blog list affects any other part of the site, please document these changes in the PR

**Comment by Sai-ganesh-0004** [comment]
I would like to try this would you like to assign it to me

**Comment by DeadmanAbir** [comment]
> I would like to try this would you like to assign it to me

okay take it

**Comment by Sai-ganesh-0004** [comment]
Hey I was working on it and I could remove the sidebar but when clicking on the blog it is showing this;

![image](https://github.com/user-attachments/assets/db8c8aca-92e4-422f-ae95-e5e48262bb0e)


I think It might be because of the `NEXT_PUBLIC_HASHNODE_HOST` you gave in `.env.sample` . And I think you have to give your actual host.
Once check and respond

**Comment by DeadmanAbir** [comment]
> Hey I was working on it and I could remove the sidebar but when clicking on the blog it is showing this;
> 
> ![image](https://private-user-images.githubusercontent.com/153413186/377163598-db8c8aca-92e4-422f-ae95-e5e48262bb0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMDQxMTQsIm5iZiI6MTcyOTEwMzgxNCwicGF0aCI6Ii8xNTM0MTMxODYvMzc3MTYzNTk4LWRiOGM4YWNhLTkyZTQtNDIyZi1hZTk1LWU1ZTQ4MjYyYmIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxODM2NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZjFmYzA0ZGZmMWU3YWNjZGUxMjkxMzdlYzhhMWUxMWZjMzQ4OTQ0ZjczZjFiM2YxMmVmYzFhMTVkZGQyNDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Tz2H1vwCcJFZkbG3awyRx7BrqiHhbsUDC0LaOELKIqQ)
> 
> I think It might be because of the `NEXT_PUBLIC_HASHNODE_HOST` you gave in `.env.sample` . And I think you have to give your actual host. Once check and respond

use `deadmanabir.hashnode.dev` as hashnode host for now

**Comment by DeadmanAbir** [comment]
any updates? @Sai-ganesh-0004

**Comment by Sai-ganesh-0004** [comment]
still working on it

**Comment by Sai-ganesh-0004** [comment]
ill update you by tomorrow

**Comment by DeadmanAbir** [comment]
> ill update you by tomorrow

updates??

**Comment by Sai-ganesh-0004** [comment]
Yeah now Im trying to solve this error

![image](https://github.com/user-attachments/assets/700f411a-d04b-44ec-9817-becf2443aad6)

**Comment by DeadmanAbir** [comment]
> Quote reply

solved or not?

**Comment by STSonyThomas** [comment]
Hey I can get this done. Could you assign it to me if the current assignee is non responsive?

**Comment by DeadmanAbir** [comment]
> Hey I can get this done. Could you assign it to me if the current assignee is non responsive?

Go ahead do it!
