### ISSUE TITLE
Adding GitHub action workflow for PR validation

### ISSUE THREAD

**Issue by ygowthamr** [DeadmanAbir/AgentGenesis#64]
**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@DeadmanAbir
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

**Comment by DeadmanAbir** [comment]
> **The workflow checks consist of following steps-**
> 
> * Should check for the PR Description in the pull request
> * Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`
> 
> @DeadmanAbir Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

take it
