### ISSUE TITLE
Enhancing Blogs PAge UI

### ISSUE THREAD

**Issue by Bhum-ika** [DeadmanAbir/AgentGenesis#67]
**Is your feature request related to a problem? Please describe.**
There is no hover effect on that page 

**Describe the solution you'd like**
I will add hover effects and Framer Motion to it

**Additional context**
![image](https://github.com/user-attachments/assets/52469eae-ce17-4157-8fb5-6a610515e13b).

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by DeadmanAbir** [comment]
Something similar is already open on #58
