### ISSUE TITLE
Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [DeadmanAbir/AgentGenesis#70]
I want to add multi language support system to the website which can help us understand in their native language.
@DeadmanAbir can you assign me this issue,

**Comment by DeadmanAbir** [comment]
> I want to add multi language support system to the website which can help us understand in their native language. @DeadmanAbir can you assign me this issue,

We use contentlayer for writing and rednering `.mdx` files. What is your approach to implement multi language system in **contentlayer**?
