### ISSUE TITLE
Redesign Footer Component

### ISSUE THREAD

**Issue by dev129** [DeadmanAbir/AgentGenesis#71]
### Issue Title
**Redesign Footer to Include Newsletter, Contact Info, and Social Links**

### Description

Currently, the footer lacks essential elements like a newsletter signup, contact information, and social media links. This makes it difficult for users to stay updated and connect with us, leading to a missed opportunity for engagement. I'm always frustrated when I can't find relevant information or connect easily with the organization.

I propose redesigning the footer to include the following sections:
- **Newsletter Signup**: A simple input field for users to enter their email address and subscribe to updates.
- **Contact Information**: Clear contact details including an email address and phone number for user inquiries.
- **Social Media Links**: Icons linking to our social media profiles (e.g., Facebook, Twitter, LinkedIn, Instagram) to enhance user engagement and community connection while the contact section remains intact.
- **Other Useful Links**: Any additional relevant links (e.g., Terms of Service, Privacy Policy).

**Additional context**  
Adding these elements to the footer will improve accessibility and enhance user interaction with our content. It would be great to see mockups or examples from other websites for inspiration on how to implement this redesign effectively.

**Comment by DeadmanAbir** [comment]
Not necessary for now.
