### ISSUE TITLE
So much gap above footer section

### ISSUE THREAD

**Issue by nishtha-902** [DeadmanAbir/AgentGenesis#72]
**Describe the bug**
so much gap above footer section
@DeadmanAbir please assign me this issue

**To Reproduce**
1. Go to 'https://agentgenesis.dev/'
2. Scroll down to 'footer'
3. See gap above footer section

**Screenshots**
![image](https://github.com/user-attachments/assets/84cc9cc6-a2fd-4904-9550-0aabacb96a60)

**Comment by DeadmanAbir** [comment]
That's because we are showing an animation there in that gap space!
