### ISSUE TITLE
Add Multiple Language Support in Footer

### ISSUE THREAD

**Issue by Priyanshu282003** [DeadmanAbir/AgentGenesis#74]
Description:
It would be great to provide users with the option to change the language of the footer to cater to a wider, more diverse audience. This feature could enhance user experience, especially for non-English speakers.

Suggested Implementation:
Add a dropdown menu or buttons in the footer for selecting languages.
Include support for common languages such as:
English
Spanish
French
Hindi
Mandarin, etc.
Ensure that the content within the footer (e.g., links, copyright, and any relevant text) changes dynamically based on the selected language.
Benefits:
Improve accessibility for users who prefer different languages.
Expand the user base by accommodating non-English speakers.

**Comment by DeadmanAbir** [comment]
> Description: It would be great to provide users with the option to change the language of the footer to cater to a wider, more diverse audience. This feature could enhance user experience, especially for non-English speakers.
> 
> Suggested Implementation: Add a dropdown menu or buttons in the footer for selecting languages. Include support for common languages such as: English Spanish French Hindi Mandarin, etc. Ensure that the content within the footer (e.g., links, copyright, and any relevant text) changes dynamically based on the selected language. Benefits: Improve accessibility for users who prefer different languages. Expand the user base by accommodating non-English speakers.

And how you are planning to implement the dynamic language change in Agentgenesis components? As they are written in `.mdx` files!
