### ISSUE TITLE
Animation: No need of unnecessary displacement of text while hover. 

### ISSUE THREAD

**Issue by userAdityaa** [DeadmanAbir/AgentGenesis#78]
**Describe the bug**
When the user hovers in the section just bottom of the feature page the text unnecessarily moves to the right side that's is not a good experience. 

**Expected behavior**
The spotlight animation should only be there with this animation removed. 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Comment by userAdityaa** [comment]
Hey @DeadmanAbir, Assign this issue to me with the label gssoc.

**Comment by DeadmanAbir** [comment]
> Hey @DeadmanAbir, Assign this issue to me with the label gssoc.
 
Share a screen recording of the problem
