### ISSUE TITLE
Integrate a Chatbot for Instant User Support

### ISSUE THREAD

**Issue by sezallagwal** [DeadmanAbir/AgentGenesis#81]
**Is your feature request related to a problem? Please describe.**
Enhance the website's user experience by integrating a chatbot that provides instant answers to user inquiries. The chatbot should be easily accessible, provide relevant responses, and offer seamless assistance for common queries, improving user engagement and support.

**Describe the solution you'd like**
Add a chatbot icon or button that floats on the bottom-right corner of the site.
When clicked, the chatbot window should expand with a smooth animation, displaying an input field and previous chat history.

The chatbot should respond to frequently asked questions (related to the FAQ section) and common inquiries about products or services.
Implement a fallback response for questions outside the chatbot's scope (e.g., "Sorry, I don't have an answer for that. Please contact our support team.").

**Describe alternatives you've considered**

**Additional context**
@DeadmanAbir please assign this to me under gssoc-ext and hacktoberfest

**Comment by DeadmanAbir** [comment]
which chatbot provider are you thinking to integrate?

**Comment by sezallagwal** [comment]
@DeadmanAbir it will be a chatbot built using gpt4o and this will be specific to the website so i can answer any questions related to the website too as well as general questions.

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir it will be a chatbot built using gpt4o. It will be a site specific chatbot which will be able to answer any queries related to site

It will be a headache for us to manage and  gather credits for api key, so not much needed for now.
