### ISSUE TITLE
Add Automated Greeting Workflow for this Github Repo

### ISSUE THREAD

**Issue by Shariq2003** [DeadmanAbir/AgentGenesis#83]
I want to create a GitHub workflow named "Greetings". 
This workflow will automatically greet users who create new issues or pull requests in this repository. 
The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Please assign me this task

**Comment by Shariq2003** [comment]
@DeadmanAbir please assign this to me.

**Comment by DeadmanAbir** [comment]
Not needed for now!
