### ISSUE TITLE
Improve Design and Styling for Blog page 

### ISSUE THREAD

**Issue by shubhagarwal1** [DeadmanAbir/AgentGenesis#84]
- Design a grid view for the page 
- Match teh design to the app 
- Align them wisely to look good 
- Add some badges to the card

Hey @DeadmanAbir please assign me this task

**Comment by DeadmanAbir** [comment]
Please checkout #58 and check if you can implement that, comment there.

**Comment by shubhagarwal1** [comment]
Sure @DeadmanAbir i can work on improving the Blog page to match the Accertinity’s blog desing, i will use shad cn and tailwind accordingly for design implementation
<img width="1433" alt="Screenshot 2024-10-24 at 1 07 08 PM" src="https://github.com/user-attachments/assets/0b915cc3-254a-4ccb-950b-94ef98cfba06">
