### ISSUE TITLE
Implement Contact us page || As of now it goes no where on Prod.

### ISSUE THREAD

**Issue by shubhagarwal1** [DeadmanAbir/AgentGenesis#85]
Add a form to the page 
this form will collect basic user data and the user question regardig contact 
we can also use google form for this purpose

**Comment by DeadmanAbir** [comment]
We have email setted up when anyone clicks on contact us.

**Comment by shubhagarwal1** [comment]
Hey @DeadmanAbir can i add another pages or work on any feature that you have planned for, would love to love work on that.
