### ISSUE TITLE
Redesign Footer, as of now it is blanck

### ISSUE THREAD

**Issue by shubhagarwal1** [DeadmanAbir/AgentGenesis#86]
<img width="1440" alt="Screenshot 2024-10-24 at 5 17 32 AM" src="https://github.com/user-attachments/assets/db81c2bf-3eb6-46b7-900d-1f29d355cee0">

**Comment by DeadmanAbir** [comment]
Hey actually it;s not blank, it has a design written Agentgenesis on bottom, switch to light mode to see it, in dark mode the visibility can depend on screen quality of machine.

**Comment by shubhagarwal1** [comment]
> Hey actually it;s not blank, it has a design written Agentgenesis on bottom, switch to light mode to see it, in dark mode the visibility can depend on screen quality of machine.

Hey @DeadmanAbir so can i revamp this to something simillar to this
<img width="1440" alt="Screenshot 2024-10-24 at 1 04 37 PM" src="https://github.com/user-attachments/assets/ecf8c81c-8271-495c-a86b-8c840c2e1238">
