### ISSUE TITLE
Adding multi language support system

### ISSUE THREAD

**Issue by amanver45** [DeadmanAbir/AgentGenesis#95]
I want to add multi language support system to the website which can help us understand in their native language.

**Comment by DeadmanAbir** [comment]
Where are you trying to place the language options?

And also how are you thinking to change the components text?

**Comment by DeadmanAbir** [comment]
> @DeadmanAbir can i work

Can you change the languages of components also?

As the components are written in mdx and is displayed using contentlayer.

**Comment by amanver45** [comment]
Try to do

**Comment by DeadmanAbir** [comment]
> Try to do

will only merge the PR if the solution also changes the component's language.

**Comment by amanver45** [comment]
@DeadmanAbir ok

**Comment by DeadmanAbir** [comment]
> Quote reply



> @DeadmanAbir ok

Are you going to do this, or I close down?

**Comment by amanver45** [comment]
@DeadmanAbir  close this
