### ISSUE TITLE
Adding cursor following animation

### ISSUE THREAD

**Issue by amanver45** [DeadmanAbir/AgentGenesis#96]
I would like to add a cursor following animation and make it align with the website styling
Kindly assign this to me

**Comment by DeadmanAbir** [comment]
can you show some glimpse of what you re trying to implement?

**Comment by DeadmanAbir** [comment]
> like this
> 
>  Recording.2024-10-28.201513.mp4

Looks good for desktops but will be problematic in mobile screens

**Comment by amanver45** [comment]
@DeadmanAbir  what about chatbot #97
