### ISSUE TITLE
add chatbot integration to website

### ISSUE THREAD

**Issue by amanver45** [DeadmanAbir/AgentGenesis#97]
add chatbot integration to website

**Comment by DeadmanAbir** [comment]
which provider your'e thinking to inetegrate?

**Comment by DeadmanAbir** [comment]
> chatbase

do we need to add our own gpt key or chatbase provides that into their free tier?

**Comment by amanver45** [comment]
Chatbase provide that but have some limit/month

**Comment by amanver45** [comment]
@DeadmanAbir  can i work on chatbot Or not?

**Comment by DeadmanAbir** [comment]
> Author

ok give it a try
