### ISSUE TITLE
feat: removing the default action

### ISSUE THREAD

**Issue by AE-Hertz** [DeadmanAbir/AgentGenesis#99]
**Is your feature request related to a problem? Please describe.**
The main hero section has a video that is a eye attraction but after hovering the video shows the details like name of the video playing showing pip button(which is not required idealy), and youtube icon.

**Describe the solution you'd like**
i will remove these things to appear on hover and also make the video to to play on loop, to have a good experience throughout.

![Screenshot 2024-10-29 202606](https://github.com/user-attachments/assets/db403ee8-e3ae-46fd-bb07-eca6d00854a3)

Assign me this issue under gssoc-ext and hacktoberfest.

**Comment by AE-Hertz** [comment]
@DeadmanAbir can you please assign me the issues.

**Comment by DeadmanAbir** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] The main hero section has a video that is a eye attraction but after hovering the video shows the details like name of the video playing showing pip button(which is not required idealy), and youtube icon.
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen. i will remove these things to appear on hover and also make the video to to play on loop, to have a good experience throughout.
> 
> ![Screenshot 2024-10-29 202606](https://private-user-images.githubusercontent.com/93651229/381183648-db403ee8-e3ae-46fd-bb07-eca6d00854a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ3OTAsIm5iZiI6MTczMDI3NDQ5MCwicGF0aCI6Ii85MzY1MTIyOS8zODExODM2NDgtZGI0MDNlZTgtZTNhZS00NmZkLWJiMDctZWNhNmQwMDg1NGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNzM1N2E5NDE0Njc4N2ZhOTYyYWQwMTA0ODY1MGUyNzcwMzJkMWY3OGYyYzBlZDJiNGM3NzkwNjIzYzcwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bzAUJkWQCMwtg6y588a1mLeeJwt0UoMghoxgxxkvHL8)
> 
> Assign me this issue under gssoc-ext and hacktoberfest.

Are you willing to solve this thing using the YouTube video link only?

**Comment by AE-Hertz** [comment]
> > **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] The main hero section has a video that is a eye attraction but after hovering the video shows the details like name of the video playing showing pip button(which is not required idealy), and youtube icon.
> > **Describe the solution you'd like** A clear and concise description of what you want to happen. i will remove these things to appear on hover and also make the video to to play on loop, to have a good experience throughout.
> > ![Screenshot 2024-10-29 202606](https://private-user-images.githubusercontent.com/93651229/381183648-db403ee8-e3ae-46fd-bb07-eca6d00854a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNzQ3OTAsIm5iZiI6MTczMDI3NDQ5MCwicGF0aCI6Ii85MzY1MTIyOS8zODExODM2NDgtZGI0MDNlZTgtZTNhZS00NmZkLWJiMDctZWNhNmQwMDg1NGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA3NDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNzM1N2E5NDE0Njc4N2ZhOTYyYWQwMTA0ODY1MGUyNzcwMzJkMWY3OGYyYzBlZDJiNGM3NzkwNjIzYzcwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bzAUJkWQCMwtg6y588a1mLeeJwt0UoMghoxgxxkvHL8)
> > Assign me this issue under gssoc-ext and hacktoberfest.
> 
> Are you willing to solve this thing using the YouTube video link only?

yes, i wont be changing the source of the video ie. youtube, i will handle the things which i mentioned through styling and for looping the change some props values.

if their is something else you can mention it too.
thank you.
